name: dart
description: An iOS-style photo gallery app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  photo_manager: ^2.8.1
  path_provider: ^2.1.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
